### ISSUE TITLE
Profil invalide

### ISSUE THREAD

**Issue by BlivionIaG** [CHEN-AND-CO/nazca#6]
**Problème**
Affichage page invalide quand on clique sur enregistrement

**Reproduire**
Suivez ces étapes
1. Aller sur 'index.php'
2. Cliquez sur 'Enregistrement'

**Comportement attendu**
Pas de réaction

**Config:**
 - OS: ArchLinux
 - Browser FireFox 59.0.2
 - Version 0.2.3

**Comment by HerrCraziDev** [comment]
Le problème vient du sélecteur utilisé en JS pour l'ajoutdes écouteurs d'event _click_

**Comment by HerrCraziDev** [comment]
Fixé.
